### ISSUE TITLE
Update spin installation instructions in README.md

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/spin#60]
See https://github.com/ausaccessfed/spin/pull/59#discussion_r25577443

Right now the readme instructions give a ```git clone``` option to install. We don't want to have this in the readme until spin is open source.

When spin is open source we need to restore the ```git clone``` instructions and completely remove the tarball instructions.

**Comment by bradleybeddoes** [comment]
Done with 1.0.0 release.
